name: splitty
description: The Pretty Bill Splitting App

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.10.0"

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  adaptive_icon_foreground: "assets/icon-foreground.png"
  adaptive_icon_background: "assets/icon-background.png"

flutter:

  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: outfit
      fonts:
        - asset: assets/fonts/outfit/Outfit-Regular.ttf
          weight: 400
        - asset: assets/fonts/outfit/Outfit-Medium.ttf
          weight: 500
        - asset: assets/fonts/outfit/Outfit-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/outfit/Outfit-Bold.ttf
          weight: 700